version: "3.8"

services:
  app:
    build: .
    container_name: media_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: media_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

